// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pokok.PropertyPortal.Infrastructure.Properties.Persistence;

#nullable disable

namespace Pokok.PropertyPortal.Infrastructure.Properties.Persistence.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    [Migration("20250828165126_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Parties.Aggregates.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("PartyType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Properties.Aggregates.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Properties.Entities.PropertyUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyUnits", (string)null);
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Residents.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PropertyUnitId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResidentRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("PropertyUnitId");

                    b.ToTable("Residents", (string)null);
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Parties.Aggregates.Party", b =>
                {
                    b.OwnsOne("Pokok.BuildingBlocks.Domain.SharedKernel.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.OwnsOne("Pokok.BuildingBlocks.Domain.SharedKernel.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.OwnsOne("Pokok.PropertyPortal.Domain.Parties.ValueObjects.PartyName", "PartyName", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PartyName");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PartyName")
                        .IsRequired();

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Properties.Aggregates.Property", b =>
                {
                    b.OwnsOne("Pokok.BuildingBlocks.Domain.SharedKernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Pokok.PropertyPortal.Domain.Properties.ValueObjects.PropertyName", "PropertyName", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PropertyName");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("PropertyName")
                        .IsRequired();
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Properties.Entities.PropertyUnit", b =>
                {
                    b.HasOne("Pokok.PropertyPortal.Domain.Properties.Aggregates.Property", null)
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Pokok.PropertyPortal.Domain.Properties.ValueObjects.UnitNumber", "UnitNumber", b1 =>
                        {
                            b1.Property<Guid>("PropertyUnitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("UnitNumber");

                            b1.HasKey("PropertyUnitId");

                            b1.ToTable("PropertyUnits");

                            b1.WithOwner()
                                .HasForeignKey("PropertyUnitId");
                        });

                    b.Navigation("UnitNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Residents.Resident", b =>
                {
                    b.HasOne("Pokok.PropertyPortal.Domain.Parties.Aggregates.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pokok.PropertyPortal.Domain.Properties.Entities.PropertyUnit", null)
                        .WithMany("Residents")
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Pokok.BuildingBlocks.Domain.SharedKernel.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("ResidentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("ResidentId");

                            b1.ToTable("Residents");

                            b1.WithOwner()
                                .HasForeignKey("ResidentId");
                        });

                    b.Navigation("Party");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Properties.Aggregates.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Pokok.PropertyPortal.Domain.Properties.Entities.PropertyUnit", b =>
                {
                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
